mindmap
  root((story))
    story vs narrative
      narrative
        examples
          my morning rountine
          instructions of how to do something
    what is a story
      a narrative
        about CHARACTERS
        dealing with a PROBLEM
        unified by a PREMISSE
        told in a STRUCTURED ORDER
    the spine
      n13["1) the protagonist's main story problem"]
        n14["#quot;no one wants to hear a story of the village of the happy people#quot; - lew hunter (1935-2023)"]
          the motivator, it should motivate someone to do something RIGHT NOW
      n16["2) the protagonist's main story goal"]
        n17["the major dramatic question (MDQ)"]
      n18["3) the path of action"]
      n19["4) the protagonist main story conflict"]
        conflict
          a state of tension which exists whenever someone or something opposes a character's actions
        force of the antagonism
        unity of opposites
      n24["5) stories stakes"]
        what they have to WIN
          this is going to give to our actor the motivation
          this makes their actions believable
          why WE should care about the situation?
        what they have to LOSE
        we fear that
      conflict creates drama
      stakes elevates our sense of drama
      we are not only curious about the story we are emotionally attached to it
    summary
      important
